#!/system/bin/sh
MODDIR=${0%/*}

if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors ]; then
 cpu_governors=/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
fi
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies ]; then
 cpu_freq=/sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies
fi
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies ]; then
 cpu_freq0=/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
fi
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq ]; then
 cpu_max=/sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
fi
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq ]; then
 cpu_min=/sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq
fi
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq ]; then
 setmin0=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq`
fi
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq ]; then
 setmin4=`cat /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_min_freq`
fi
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq ]; then
 setmax0=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq`
fi
if [ -e /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq ]; then
 setmax4=`cat /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq`
fi
if [ -e /sys/block/mmcblk0/queue/scheduler ]; then
 io_scheduler=/sys/block/mmcblk0/queue/scheduler
fi
ext4blocks="/sys/fs/ext4/mmcblk0p*"

# Akira #WeAreRavenS
# Modified Gaming Mode Script from @HafizZiq
while true; do
 sleep 20
 if [ $(top -n 1 -d 1 | head -n 12 | grep -o -e 'mobile' -e 'skynet' -e 'cputhrottlingtest' -e 'codm' -e 'legends' -e 'nexon' -e 'ea.game' -e 'konami' -e 'bandainamco' -e 'netmarble' -e 'GoogleCam' -e 'edengames' -e 'camera' -e 'snapcam' -e 'tencent' -e 'moonton' -e 'gameloft' -e 'netease' -e 'garena' -e 'epic' | head -n 1) ]; then
            echo "performance" > /sys/class/devfreq/cc00000.qcom,vidc:venus_bus_ddr/governor
            echo "performance" > /sys/class/devfreq/mmc0/governor
            echo "performance" > /sys/class/devfreq/mmc1/governor
            echo "performance" > /sys/class/devfreq/soc:devfreq_spdm_cpu/governor
            echo "performance" > /sys/class/devfreq/soc:qcom,cpubw/governor
            echo "performance" > /sys/class/devfreq/soc:qcom,gpubw/governor
            echo "performance" > /sys/class/devfreq/soc:qcom,kgsl-busmon/governor
            echo "performance" > /sys/class/devfreq/soc:qcom,memlat-cpu0/governor
            echo "performance" > /sys/class/devfreq/soc:qcom,memlat-cpu4/governor
            echo "performance" > /sys/class/devfreq/soc:qcom,mincpubw/governor

echo 0-7 > /dev/cpuset/audio-app/cpus
echo 0-7 > /dev/cpuset/top-app/cpus
echo 0-7 > /dev/cpuset/foreground/cpus
echo 0-7 > /dev/cpuset/background/cpus
echo 0-7 > /dev/cpuset/system-background/cpus
echo 0-7 > /dev/cpuset/restricted/cpus

echo "1" > /sys/class/kgsl/kgsl-3d0/force_clk_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_bus_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_rail_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_no_nap

write /dev/stune/background/schedtune.boost "40"
write /dev/stune/background/schedtune.prefer_idle "0"
write /dev/stune/background/schedtune.colocate "0"
write /dev/stune/background/schedtune.sched_boost_enabled "0"

write /dev/stune/foreground/schedtune.boost "40"
write /dev/stune/foreground/schedtune.prefer_idle "0"
write /dev/stune/foreground/schedtune.colocate "0"
write /dev/stune/foreground/schedtune.sched_boost_enabled "0"

write /dev/stune/rt/schedtune.boost "40"
write /dev/stune/rt/schedtune.prefer_idle "0"
write /dev/stune/rt/schedtune.colocate "0"
write /dev/stune/rt/schedtune.sched_boost_enabled "0"

write /dev/stune/top-app/schedtune.boost "40"
write /dev/stune/top-app/schedtune.prefer_idle "0"
write /dev/stune/top-app/schedtune.colocate "0"
write /dev/stune/top-app/schedtune.sched_boost_enabled "0"

write /dev/stune/schedtune.boost "40"
write /dev/stune/schedtune.prefer_idle "0"
write /dev/stune/schedtune.colocate "0"
write /dev/stune/schedtune.sched_boost_enabled "0"

 else
 fi;
done
