#!/system/bin/sh
# By @NotZeetaa

echo "100" > /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu1/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu2/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu3/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu5/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu6/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu7/cpufreq/schedutil/down_rate_limit_us

echo "200" > /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu1/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu1/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu2/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu3/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu3/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu5/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu5/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu6/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu6/cpufreq/interactive/fast_ramp_down
echo "200" > /sys/devices/system/cpu/cpu7/cpufreq/schedutil/up_rate_limit_us
echo "0" > /sys/devices/system/cpu/cpu7/cpufreq/interactive/fast_ramp_down

# Better Battery Efficient
echo "N" > /sys/module/workqueue/parameters/power_efficient

# Adreno Idler
echo "N" > /sys/module/adreno_idler/paremeters/adreno_idler_active

# Cpu Input Boost
echo "1" > /sys/module/cpu_input_boost/parameters/input_boost_duration
echo "1" > /sys/module/cpu_input_boost/parameters/dynamic_stune_boost_duration
echo "20" > /sys/module/cpu_input_boost/parameters/dynamic_stune_boost

# Gpu Tweaks
echo "0" > /sys/class/kgsl/kgsl-3d0/throttling
echo "1" > /sys/class/kgsl/kgsl-3d0/default_pwrlevel
echo "1" > /sys/class/kgsl/kgsl-3d0/force_clk_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_bus_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_rail_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_no_nap

# Scheduler
echo "cfq" > /sys/block/sda/queue/scheduler
echo "cfq" > /sys/block/sdb/queue/scheduler
echo "cfq" > /sys/block/sdc/queue/scheduler
echo "cfq" > /sys/block/sdd/queue/scheduler
echo "cfq" > /sys/block/sde/queue/scheduler
echo "cfq" > /sys/block/sdf/queue/scheduler

# Dev Stune Boost
# Fast Sensivity in Game
echo "5" > /dev/stune/background/schedtune.boost
echo "5" > /dev/stune/foreground/schedtune.boost
echo "5" > /dev/stune/rt/schedtune.boost
echo "5" > /dev/stune/top-app/schedtune.boost
echo "5" > /dev/stune/schedtune.boost

# Fs
echo "0" > /proc/sys/fs/dir-notify-enable
echo "15" > /proc/sys/fs/lease-break-time
echo "131072" > /proc/sys/fs/aio-max-nr

# Entropy config
echo '64' > /proc/sys/kernel/random/read_wakeup_threshold
echo '64' > /proc/sys/kernel/random/write_wakeup_threshold


# Scheduler features
echo "NEXT_BUDDY" > /sys/kernel/debug/sched_features
echo "NO_TTWU"QUEUE" /sys/kernel/debug/sched_features
echo "NO_WAKEUP_PREEMPTION" > /sys/kernel/debug/sched_features
echo "NO_GENTLE_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features



