#!/system/bin/sh
# By @NotZeetaa

echo "100" > /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu1/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu2/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu3/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu5/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu6/cpufreq/schedutil/down_rate_limit_us
echo "100" > /sys/devices/system/cpu/cpu7/cpufreq/schedutil/down_rate_limit_us

echo "200" > /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu1/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu2/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu3/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu5/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu6/cpufreq/schedutil/up_rate_limit_us
echo "200" > /sys/devices/system/cpu/cpu7/cpufreq/schedutil/up_rate_limit_us


# Better Battery Efficient
write /sys/module/workqueue/parameters/power_efficient "N"

# Adreno Idler
write /sys/module/adreno_idler/paremeters/adreno_idler_active "N"

# Force Fast Charge
write /sys/kernel/fast_charge/force_fast_charge "1"

# Cpu Input Boost
write /sys/module/cpu_input_boost/parameters/input_boost_duration "1"
write /sys/module/cpu_input_boost/parameters/dynamic_stune_boost_duration "1"
write /sys/module/cpu_input_boost/parameters/dynamic_stune_boost "20"

# Gpu Tweaks
echo "0" > /sys/class/kgsl/kgsl-3d0/throttling
echo "1" > /sys/class/kgsl/kgsl-3d0/default_pwrlevel
echo "1" > /sys/class/kgsl/kgsl-3d0/force_clk_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_bus_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_rail_on
echo "1" > /sys/class/kgsl/kgsl-3d0/force_no_nap

# Scheduler
write /sys/block/sda/queue/scheduler "cfq"
write /sys/block/sdb/queue/scheduler "cfq"
write /sys/block/sdc/queue/scheduler "cfq"
write /sys/block/sdd/queue/scheduler "cfq"
write /sys/block/sde/queue/scheduler "cfq"
write /sys/block/sdf/queue/scheduler "cfq"

# Dev Stune Boost
# Fast Sensivity in Game
write /dev/stune/background/schedtune.boost "15"
write /dev/stune/background/schedtune.prefer_idle "0"
write /dev/stune/background/schedtune.colocate "0"
write /dev/stune/background/schedtune.sched_boost_enabled "0"

write /dev/stune/foreground/schedtune.boost "15"
write /dev/stune/foreground/schedtune.prefer_idle "0"
write /dev/stune/foreground/schedtune.colocate "0"
write /dev/stune/foreground/schedtune.sched_boost_enabled "0"

write /dev/stune/rt/schedtune.boost "15"
write /dev/stune/rt/schedtune.prefer_idle "0"
write /dev/stune/rt/schedtune.colocate "0"
write /dev/stune/rt/schedtune.sched_boost_enabled "0"

write /dev/stune/top-app/schedtune.boost "15"
write /dev/stune/top-app/schedtune.prefer_idle "0"
write /dev/stune/top-app/schedtune.colocate "0"
write /dev/stune/top-app/schedtune.sched_boost_enabled "0"

write /dev/stune/schedtune.boost "15"
write /dev/stune/schedtune.prefer_idle "0"
write /dev/stune/schedtune.colocate "0"
write /dev/stune/schedtune.sched_boost_enabled "0"

# Fs
write /proc/sys/fs/dir-notify-enable "0"
write /proc/sys/fs/lease-break-time "15"
write /proc/sys/fs/aio-max-nr "131072"

# Entropy config
echo '64' > /proc/sys/kernel/random/read_wakeup_threshold
echo '64' > /proc/sys/kernel/random/write_wakeup_threshold


# Scheduler features
if [[ -f "/sys/kernel/debug/sched_features" ]]
then
	write /sys/kernel/debug/sched_features NEXT_BUDDY
	write /sys/kernel/debug/sched_features NO_TTWU_QUEUE
   write /sys/kernel/debug/sched_features NO_WAKEUP_PREEMPTION
   write /sys/kernel/debug/sched_features NO_GENTLE_FAIR_SLEEPERS
fi

  # Blu-schedutil Tweaks
  if [[ -d "${cpu}blu_schedutil" ]]
  then
    write "${cpu}blu_schedutil/up_rate_limit_us" 200
	  write "${cpu}blu_schedutil/down_rate_limit_us" 4500
    write "${cpu}blu_schedutil/hispeed_freq" `cat "${cpu}cpuinfo_max_freq"`
  fi
done


dbg "Finished with $ERR_CNT failed writes."
